Repository Team-MansuMugang/mansumugang-backend, pull requests merged in 2024-08, with the labels that each got.

#48 약 관리 기능 구현
  .gitignore
  Dockerfile
  src/main/java/org/mansumugang/mansumugang_service/MansumugangServiceApplication.java
  src/main/java/org/mansumugang/mansumugang_service/ScheduledTasks.java
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/constant/InternalErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/constant/LocationBoundary.java
  src/main/java/org/mansumugang/mansumugang_service/controller/auth/AuthController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/medicine/MedicineController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/medicine/MedicineIntakeController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/user/PatientLocationController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/Medicine.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicineInTakeTime.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicineIntakeDay.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicineIntakeRecord.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/Patient.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/Protector.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/User.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/UserLocation.java
  src/main/java/org/mansumugang/mansumugang_service/dto/auth/signup/PatientSignupRequestDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/auth/signup/ProtectorSignUpRequestDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/auth/signup/SignUpDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSchedule.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSummaryInfoDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicineIntake/MedicineIntakeToggleDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicineIntake/MedicineIntakeToggleRequestDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicineIntake/MedicineIntakeToggleResponseDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/location/PatientLocationDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/location/PatientLocationRequestDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/location/PatientLocationResponseDto.java
  src/main/java/org/mansumugang/mansumugang_service/exception/CustomNotValidErrorException.java
  src/main/java/org/mansumugang/mansumugang_service/exception/InternalErrorException.java
  src/main/java/org/mansumugang/mansumugang_service/exception/NotValidRequestErrorResponseDto.java
  src/main/java/org/mansumugang/mansumugang_service/filter/JwtAuthenticationFilter.java
  src/main/java/org/mansumugang/mansumugang_service/handler/GlobalExceptionHandler.java
  src/main/java/org/mansumugang/mansumugang_service/repository/MedicineIntakeDayRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/MedicineIntakeRecordRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/MedicineIntakeTimeRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/MedicineRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/PatientRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/ProtectorRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/UserLocationRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/UserRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/auth/CustomUserDetailsService.java
  src/main/java/org/mansumugang/mansumugang_service/service/auth/LogoutService.java
  src/main/java/org/mansumugang/mansumugang_service/service/auth/ReIssueTokenService.java
  src/main/java/org/mansumugang/mansumugang_service/service/auth/SignupService.java
  src/main/java/org/mansumugang/mansumugang_service/service/fileService/FileService.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineIntakeService.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineService.java
  src/main/java/org/mansumugang/mansumugang_service/service/user/UserLocationService.java
  src/main/java/org/mansumugang/mansumugang_service/utils/DateParser.java
  src/main/java/org/mansumugang/mansumugang_service/validation/DateValidator.java
  src/main/java/org/mansumugang/mansumugang_service/validation/ValidDate.java
  src/main/resources/application.yaml
Labels: enhancement

#52 약 관리 기능 구현
  .gitignore
  Dockerfile
  src/main/java/org/mansumugang/mansumugang_service/MansumugangServiceApplication.java
  src/main/java/org/mansumugang/mansumugang_service/ScheduledTasks.java
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/constant/InternalErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/medicine/MedicineController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/medicine/MedicineIntakeController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/Medicine.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicineInTakeTime.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicineIntakeDay.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicineIntakeRecord.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/User.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSchedule.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSummaryInfoDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicineIntake/MedicineIntakeToggleDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicineIntake/MedicineIntakeToggleRequestDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicineIntake/MedicineIntakeToggleResponseDto.java
  src/main/java/org/mansumugang/mansumugang_service/exception/CustomNotValidErrorException.java
  src/main/java/org/mansumugang/mansumugang_service/exception/InternalErrorException.java
  src/main/java/org/mansumugang/mansumugang_service/repository/MedicineIntakeDayRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/MedicineIntakeRecordRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/MedicineIntakeTimeRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/MedicineRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/fileService/FileService.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineIntakeService.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineService.java
  src/main/java/org/mansumugang/mansumugang_service/utils/DateParser.java
  src/main/java/org/mansumugang/mansumugang_service/validation/DateValidator.java
  src/main/java/org/mansumugang/mansumugang_service/validation/ValidDate.java
Labels: enhancement

#56 약 조회 기능 개선
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/constant/MedicineRecordStatusType.java
  src/main/java/org/mansumugang/mansumugang_service/constant/MedicineStatusType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/medicine/MedicineController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicineIntakeRecord.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSchedule.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSummaryInfo.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSummaryInfoResult.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicineIntake/MedicineIntakeToggleDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicineIntake/MedicineIntakeToggleResponseDto.java
  src/main/java/org/mansumugang/mansumugang_service/repository/MedicineIntakeRecordRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineCommonService.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineIntakeService.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineService.java
Labels: enhancement

#58 개선된 약 관련기능을 develop 브랜치에 병합 요청
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/constant/MedicineRecordStatusType.java
  src/main/java/org/mansumugang/mansumugang_service/constant/MedicineStatusType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/medicine/MedicineController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicineIntakeRecord.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSchedule.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSummaryInfo.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSummaryInfoResult.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicineIntake/MedicineIntakeToggleDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicineIntake/MedicineIntakeToggleResponseDto.java
  src/main/java/org/mansumugang/mansumugang_service/repository/MedicineIntakeRecordRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineCommonService.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineIntakeService.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineService.java
Labels: enhancement

#54 46번 이슈에 대한 일부 코드 구현입니다.
  build.gradle
  src/main/java/org/mansumugang/mansumugang_service/config/MultipartConfig.java
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/constant/InternalErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/record/RecordController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/user/PatientLocationController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/location/Location.java
  src/main/java/org/mansumugang/mansumugang_service/domain/record/Record.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/Patient.java
  src/main/java/org/mansumugang/mansumugang_service/dto/location/PatientLocation.java
  src/main/java/org/mansumugang/mansumugang_service/dto/location/PatientLocationList.java
  src/main/java/org/mansumugang/mansumugang_service/dto/location/PatientLocationRequestDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordSave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/location/PatientLocationDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/location/PatientLocationResponseDto.java
  src/main/java/org/mansumugang/mansumugang_service/repository/RecordRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/UserLocationRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/fileService/FileService.java
  src/main/java/org/mansumugang/mansumugang_service/service/location/UserLocationService.java
  src/main/java/org/mansumugang/mansumugang_service/service/record/RecordService.java
Labels: enhancement

#59 Feature/voice recording -> develop 브랜치 병합요청
  build.gradle
  src/main/java/org/mansumugang/mansumugang_service/config/MultipartConfig.java
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/constant/InternalErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/record/RecordController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/user/PatientLocationController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/location/Location.java
  src/main/java/org/mansumugang/mansumugang_service/domain/record/Record.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/Patient.java
  src/main/java/org/mansumugang/mansumugang_service/dto/location/PatientLocation.java
  src/main/java/org/mansumugang/mansumugang_service/dto/location/PatientLocationList.java
  src/main/java/org/mansumugang/mansumugang_service/dto/location/PatientLocationRequestDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordSave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/location/PatientLocationDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/location/PatientLocationResponseDto.java
  src/main/java/org/mansumugang/mansumugang_service/repository/RecordRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/UserLocationRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/fileService/FileService.java
  src/main/java/org/mansumugang/mansumugang_service/service/location/UserLocationService.java
  src/main/java/org/mansumugang/mansumugang_service/service/record/RecordService.java
Labels: enhancement

#61 60번 이슈에 대한 코드 수정 완료
  src/main/java/org/mansumugang/mansumugang_service/service/fileService/FileService.java
  src/main/java/org/mansumugang/mansumugang_service/service/record/RecordService.java
Labels: bug

#62 60-fix-bug-for-vocie-recording -> develop 브랜치 병합 요창
  src/main/java/org/mansumugang/mansumugang_service/service/fileService/FileService.java
  src/main/java/org/mansumugang/mansumugang_service/service/record/RecordService.java
Labels: bug

#65 변경된 약 조회 기능 스펙을 develop 브랜치와 병합
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSummaryInfo.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineService.java
Labels: enhancement

#67 보호자 메인페이지 - 보호자의 환자 찾기 구현
  src/main/java/org/mansumugang/mansumugang_service/controller/user/UserController.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/PatientInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/service/user/UserService.java
Labels: enhancement

#69 약 미복용 환자 관리 기능 구현
  src/main/java/org/mansumugang/mansumugang_service/ScheduledTasks.java
  src/main/java/org/mansumugang/mansumugang_service/constant/InternalErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicineIntakeRecord.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/TodayMedicineScheduleResult.java
  src/main/java/org/mansumugang/mansumugang_service/repository/MedicineIntakeRecordRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineCommonService.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/ScheduledTasks.java
Labels: enhancement

#70 구현한 약 미복용 환자 관리 기능을 develop 브랜치에 병합 요청
  src/main/java/org/mansumugang/mansumugang_service/ScheduledTasks.java
  src/main/java/org/mansumugang/mansumugang_service/constant/InternalErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicineIntakeRecord.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/TodayMedicineScheduleResult.java
  src/main/java/org/mansumugang/mansumugang_service/repository/MedicineIntakeRecordRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineCommonService.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/ScheduledTasks.java
Labels: enhancement

#76 약 기능 버그 수정 및 개선
  Dockerfile
  src/main/java/org/mansumugang/mansumugang_service/controller/medicine/MedicineController.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSummaryInfo.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineService.java
Labels: bug, enhancement

#77 약 기능 버그 수정 및 개선
  Dockerfile
  src/main/java/org/mansumugang/mansumugang_service/controller/medicine/MedicineController.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSummaryInfo.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineService.java
Labels: bug, enhancement

#79 오류를 찾기위한 로그 추가
  src/main/java/org/mansumugang/mansumugang_service/controller/record/RecordController.java
  src/main/java/org/mansumugang/mansumugang_service/service/fileService/FileService.java
  src/main/java/org/mansumugang/mansumugang_service/service/record/RecordService.java
Labels: bug

#80 log-for-voice-recording -> develop 브랜치 병합 요청
  src/main/java/org/mansumugang/mansumugang_service/controller/record/RecordController.java
  src/main/java/org/mansumugang/mansumugang_service/service/fileService/FileService.java
  src/main/java/org/mansumugang/mansumugang_service/service/record/RecordService.java
Labels: bug

#85 구현한 약 상세정보 기능을 develop 브랜치에 병합
  src/main/java/org/mansumugang/mansumugang_service/controller/medicine/MedicineController.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineDetailGet.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineService.java
Labels: enhancement

#87 구현한 환자의 병원 방문 일정관리 기능을 develop 브랜치에 병합 요청
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/hospital/HospitalController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/hospital/Hospital.java
  src/main/java/org/mansumugang/mansumugang_service/dto/hospital/HospitalDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/hospital/HospitalDetailGet.java
  src/main/java/org/mansumugang/mansumugang_service/dto/hospital/HospitalSave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/hospital/HospitalUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSummaryInfo.java
  src/main/java/org/mansumugang/mansumugang_service/repository/HospitalRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/hospital/HospitalService.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineService.java
Labels: enhancement

#88 특정일 스케줄 조회 시 약 정보가 없을 경우 오류가 발생하는 버그 수정
  src/main/java/org/mansumugang/mansumugang_service/constant/ScheduleToggleType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/medicine/PatientScheduleController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/hospital/Hospital.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSummaryInfo.java
  src/main/java/org/mansumugang/mansumugang_service/dto/patientScheduleToggle/PatientScheduleToggle.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/PatientScheduleService.java
Labels: bug

#89 병원 방문 기능과 관련된 버그 수정 및 추가적인 기능을 develop 브랜치에 병합
  src/main/java/org/mansumugang/mansumugang_service/constant/ScheduleToggleType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/medicine/PatientScheduleController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/hospital/Hospital.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineSummaryInfo.java
  src/main/java/org/mansumugang/mansumugang_service/dto/patientScheduleToggle/PatientScheduleToggle.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/PatientScheduleService.java
Labels: bug, enhancement

#92 FCM을 이용한 웹 푸시 알림 기능 구현
  .gitignore
  build.gradle
  src/main/java/org/mansumugang/mansumugang_service/config/FirebaseConfig.java
  src/main/java/org/mansumugang/mansumugang_service/config/SecurityConfig.java
  src/main/java/org/mansumugang/mansumugang_service/controller/fcm/FcmController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/fcm/FcmToken.java
  src/main/java/org/mansumugang/mansumugang_service/domain/hospital/Hospital.java
  src/main/java/org/mansumugang/mansumugang_service/dto/auth/login/LoginRequestDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/fcm/FcmMessage.java
  src/main/java/org/mansumugang/mansumugang_service/dto/fcm/FcmTokenSave.java
  src/main/java/org/mansumugang/mansumugang_service/repository/FcmTokenRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/HospitalRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/fcm/FcmService.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/ScheduledTasks.java
Labels: enhancement

#94 gradle.yml 내용 변경
  .github/workflows/gradle.yml
Labels: enhancement

#95 FCM 백앤드 연결 코드 변경
  src/main/java/org/mansumugang/mansumugang_service/config/FirebaseConfig.java
Labels: enhancement

#96 FCM Json 파일을 SCP를 통해 서버로 전송하는 코드 추가
  .github/workflows/gradle.yml
Labels: enhancement

#97 echo 명령어 대신 printf 명령어 사용
  .github/workflows/gradle.yml
Labels: enhancement

#98 FCM Json 파일 생성 로직 수정
  .github/workflows/gradle.yml
Labels: enhancement

#100 SCP 제거
  .github/workflows/gradle.yml
Labels: enhancement

#101 Json 파일 생성 step 이름 변경
  .github/workflows/gradle.yml
Labels: enhancement

#93 Feature/notification -> develop 브랜치 병합 요청
  .github/workflows/gradle.yml
  .gitignore
  build.gradle
  src/main/java/org/mansumugang/mansumugang_service/config/FirebaseConfig.java
  src/main/java/org/mansumugang/mansumugang_service/config/SecurityConfig.java
  src/main/java/org/mansumugang/mansumugang_service/controller/fcm/FcmController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/fcm/FcmToken.java
  src/main/java/org/mansumugang/mansumugang_service/domain/hospital/Hospital.java
  src/main/java/org/mansumugang/mansumugang_service/dto/auth/login/LoginRequestDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/fcm/FcmMessage.java
  src/main/java/org/mansumugang/mansumugang_service/dto/fcm/FcmTokenSave.java
  src/main/java/org/mansumugang/mansumugang_service/repository/FcmTokenRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/HospitalRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/fcm/FcmService.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/ScheduledTasks.java
Labels: enhancement

#104 약 조회 시 이미지를 포함하도록 스펙 변경
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineDetailGet.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineService.java
Labels: enhancement

#105 변경된 약 조회 스펙을 develop 브랜치에 병합 요청
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicineDetailGet.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineService.java
Labels: enhancement

#107 Production Server CI/CD 구축
  .github/workflows/prod-gradle.yml
  .gitignore
  appspec.yaml
Labels: enhancement

#110 bash 파일이 실행안되도록 조치
  .github/workflows/prod-gradle.yml
Labels: bug

#111 syntax error 해결
  .github/workflows/prod-gradle.yml
Labels: bug

#112 쉘 파일 실행 안되도록 설정
  .github/workflows/prod-gradle.yml
Labels: bug

#113 deploy.sh 파일 인코딩 이용
  .github/workflows/prod-gradle.yml
Labels: bug

#114 appspec.yml 이름 변경
  appspec.yml
Labels: refactor

#115 appspec.yml 파일의 deploy destination 수정
  appspec.yml
Labels: enhancement

#116 Production 환경에서의 AWS S3 구성
  build.gradle
  src/main/java/org/mansumugang/mansumugang_service/config/S3Config.java
  src/main/java/org/mansumugang/mansumugang_service/constant/FileType.java
  src/main/java/org/mansumugang/mansumugang_service/constant/InternalErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/service/fileService/S3FileService.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicineService.java
  src/main/java/org/mansumugang/mansumugang_service/service/record/RecordService.java
  src/main/java/org/mansumugang/mansumugang_service/utils/ProfileChecker.java
Labels: enhancement

#117 누락된 프로파일 추가
  .github/workflows/prod-gradle.yml
Labels: enhancement

#119 컨테이너 내 정적 파일 공간 생성
  Dockerfile
Labels: bug

#120 컨테이너 내 정적 파일 공간 생성
  Dockerfile
Labels: bug

#122 Origin 등록
  src/main/java/org/mansumugang/mansumugang_service/config/SecurityConfig.java
Labels: enhancement

#123 등록한 Origin을 develop 브랜치에 병합
  src/main/java/org/mansumugang/mansumugang_service/config/SecurityConfig.java
Labels: enhancement

#126 Origin 등록
  src/main/java/org/mansumugang/mansumugang_service/config/SecurityConfig.java
Labels: enhancement

#127 커뮤니티 관련 기능 구현 완료
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/constant/PostCategoryCode.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/CommentController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/PostController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/PostImageController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/PostInteractionController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/ReplyController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Comment.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Post.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/PostBookmark.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/PostCategory.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/PostImage.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/PostLike.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Reply.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/Protector.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/comment/CommentDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/comment/CommentInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/comment/CommentSave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/comment/CommentUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostSave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostUtil.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/postCategory/PostCategoryInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/postImage/PostImageSave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/postInteraction/PostInteraction.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/reply/ReplyDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/reply/ReplyInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/reply/ReplySave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/reply/ReplyUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/repository/CommentRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/PostBookmarkRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/PostCategoryRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/PostImageRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/PostLikeRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/PostRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/ReplyRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/CommentService.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/ReplyService.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/post/PostService.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/postIneraction/PostInteractionService.java
  src/main/java/org/mansumugang/mansumugang_service/service/fcm/FcmService.java
  src/main/java/org/mansumugang/mansumugang_service/service/fileService/FileService.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/ScheduledTasks.java
Labels: enhancement

#128 Feature/community -> devleop 브랜치로 병합 요청
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/constant/PostCategoryCode.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/CommentController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/PostController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/PostImageController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/PostInteractionController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/ReplyController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Comment.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Post.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/PostBookmark.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/PostCategory.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/PostImage.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/PostLike.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Reply.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/Protector.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/comment/CommentDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/comment/CommentInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/comment/CommentSave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/comment/CommentUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostSave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostUtil.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/postCategory/PostCategoryInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/postImage/PostImageSave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/postInteraction/PostInteraction.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/reply/ReplyDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/reply/ReplyInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/reply/ReplySave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/reply/ReplyUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/repository/CommentRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/PostBookmarkRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/PostCategoryRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/PostImageRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/PostLikeRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/PostRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/ReplyRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/CommentService.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/ReplyService.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/post/PostService.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/postIneraction/PostInteractionService.java
  src/main/java/org/mansumugang/mansumugang_service/service/fcm/FcmService.java
  src/main/java/org/mansumugang/mansumugang_service/service/fileService/FileService.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/ScheduledTasks.java
Labels: enhancement

#130 보호자 자기자신 정보 조회 기능 구현
  src/main/java/org/mansumugang/mansumugang_service/controller/user/UserController.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/ProtectorInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/service/user/UserService.java
Labels: enhancement

#131 Feature/inquiry-protector-own-info -> devlop 브랜치 병합 요청
  src/main/java/org/mansumugang/mansumugang_service/controller/user/UserController.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/ProtectorInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/service/user/UserService.java
Labels: enhancement

#133 보호자 본인 정보 조회 기능 코드 수정
  src/main/java/org/mansumugang/mansumugang_service/service/fileService/FileService.java
  src/main/java/org/mansumugang/mansumugang_service/service/user/UserService.java
Labels: refactor

#134 Feature/inquiry-protector-own-info -> devleop 브랜치으로 병합 요청
  src/main/java/org/mansumugang/mansumugang_service/service/fileService/FileService.java
  src/main/java/org/mansumugang/mansumugang_service/service/user/UserService.java
Labels: refactor

#136 Multipart 최대 전송 가능 크기 증량
  src/main/java/org/mansumugang/mansumugang_service/config/MultipartConfig.java
Labels: enhancement

#137 증량한 Multipart 최대 전송 가능 크기를 develop 브랜치에 병합
  src/main/java/org/mansumugang/mansumugang_service/config/MultipartConfig.java
Labels: enhancement

#138 커뮤니티 기능 향상을 위한 기능 및 회원 기능 추가.
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/constant/FileType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/CommentController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/PostController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/PostImageController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/ReplyController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/SearchController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/user/UserController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/Patient.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/Protector.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/User.java
  src/main/java/org/mansumugang/mansumugang_service/dto/auth/signup/PatientSignupRequestDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/auth/signup/ProtectorSignUpRequestDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostUtil.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/reply/ReplyInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/search/Search.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/PatientInfoInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/PatientInfoUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/ProtectorInfoInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/ProtectorInfoUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/repository/PostRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/CommentService.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/ReplyService.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/SearchService.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/post/PostService.java
  src/main/java/org/mansumugang/mansumugang_service/service/fileService/FileService.java
  src/main/java/org/mansumugang/mansumugang_service/service/fileService/S3FileService.java
  src/main/java/org/mansumugang/mansumugang_service/service/user/UserService.java
  src/main/resources/application.yaml
Labels: enhancement

#139 Feature/community -> develop 브랜치 병합 요청
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/constant/FileType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/CommentController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/PostController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/PostImageController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/ReplyController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/SearchController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/user/UserController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/Patient.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/Protector.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/User.java
  src/main/java/org/mansumugang/mansumugang_service/dto/auth/signup/PatientSignupRequestDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/auth/signup/ProtectorSignUpRequestDto.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostUtil.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/reply/ReplyInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/search/Search.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/PatientInfoInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/PatientInfoUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/ProtectorInfoInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/ProtectorInfoUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/repository/PostRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/CommentService.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/ReplyService.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/SearchService.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/post/PostService.java
  src/main/java/org/mansumugang/mansumugang_service/service/fileService/S3FileService.java
  src/main/java/org/mansumugang/mansumugang_service/service/user/UserService.java
  src/main/resources/application.yaml
Labels: enhancement

#125 처방전 공유 기능 구현
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/medicine/MedicinePrescriptionController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicinePrescription.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicinePrescriptionDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicinePrescriptionListGet.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicinePrescriptionSave.java
  src/main/java/org/mansumugang/mansumugang_service/repository/MedicinePrescriptionRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicinePrescriptionService.java
Labels: enhancement

#140 구현한 처방전 공유기능을 develop 브랜치에 병합 요청
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/medicine/MedicinePrescriptionController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicinePrescription.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicinePrescriptionDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicinePrescriptionListGet.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicinePrescriptionSave.java
  src/main/java/org/mansumugang/mansumugang_service/repository/MedicinePrescriptionRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicinePrescriptionService.java
Labels: enhancement

#142 환자의 가족관계 조회 기능 구현
  build.gradle
  src/main/java/org/mansumugang/mansumugang_service/controller/user/UserController.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/FamilyMember.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/FamilyMemberInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/service/user/UserService.java
Labels: enhancement

#143 Enhance-for-user -> develop 브랜치 병합 요청
  build.gradle
  src/main/java/org/mansumugang/mansumugang_service/controller/user/UserController.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/FamilyMember.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/FamilyMemberInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/service/user/UserService.java
Labels: enhancement

#144 게시물 상세 정보 조회시 본인의 좋아요 누름 판단 확인 로직 추가
  src/main/java/org/mansumugang/mansumugang_service/domain/community/PostLike.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/repository/PostLikeRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/post/PostService.java
Labels: enhancement

#145 Enhance-for-user -> develop 브랜치로 병합 요청
  src/main/java/org/mansumugang/mansumugang_service/domain/community/PostLike.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/repository/PostLikeRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/post/PostService.java
Labels: enhancement

#146 회원 탈퇴 기능 구현
  src/main/java/org/mansumugang/mansumugang_service/controller/user/UserController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/hospital/Hospital.java
  src/main/java/org/mansumugang/mansumugang_service/domain/location/Location.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/Medicine.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicineInTakeTime.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicineIntakeDay.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicineIntakeRecord.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicinePrescription.java
  src/main/java/org/mansumugang/mansumugang_service/domain/record/Record.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/Patient.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/Protector.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/User.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/familyMember/FamilyMember.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/familyMember/FamilyMemberInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/infoDelete/PatientInfoDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/infoDelete/ProtectorInfoDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/infoUpdate/PatientInfoUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/infoUpdate/ProtectorInfoUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/inquiry/PatientInfoInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/inquiry/PatientInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/inquiry/ProtectorInfoInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/repository/MedicinePrescriptionRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/MedicineRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/RecordRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/user/UserService.java
Labels: enhancement

#147 Enhance-for-user -> develop 브랜치로 병합 요청
  src/main/java/org/mansumugang/mansumugang_service/controller/user/UserController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/hospital/Hospital.java
  src/main/java/org/mansumugang/mansumugang_service/domain/location/Location.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/Medicine.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicineInTakeTime.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicineIntakeDay.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicineIntakeRecord.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/MedicinePrescription.java
  src/main/java/org/mansumugang/mansumugang_service/domain/record/Record.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/Patient.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/Protector.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/User.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/familyMember/FamilyMember.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/familyMember/FamilyMemberInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/infoDelete/PatientInfoDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/infoDelete/ProtectorInfoDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/infoUpdate/PatientInfoUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/infoUpdate/ProtectorInfoUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/inquiry/PatientInfoInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/inquiry/PatientInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/inquiry/ProtectorInfoInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/repository/MedicinePrescriptionRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/MedicineRepository.java
  src/main/java/org/mansumugang/mansumugang_service/repository/RecordRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/user/UserService.java
Labels: enhancement

#148 보호자 회원 탈퇴 기능 구현 완료
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/user/UserController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Comment.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Post.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/PostBookmark.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/PostLike.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Reply.java
  src/main/java/org/mansumugang/mansumugang_service/domain/fcm/FcmToken.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/infoDelete/ProtectorInfoDelete.java
  src/main/java/org/mansumugang/mansumugang_service/repository/PostRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/user/UserService.java
Labels: enhancement

#149 Enhance-for-user -> develop 브랜치로 병합 요청
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/user/UserController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Comment.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Post.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/PostBookmark.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/PostLike.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Reply.java
  src/main/java/org/mansumugang/mansumugang_service/domain/fcm/FcmToken.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/infoDelete/ProtectorInfoDelete.java
  src/main/java/org/mansumugang/mansumugang_service/repository/PostRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/user/UserService.java
Labels: enhancement

#151 처방전 정보가 없을 때 500 에러가 발생하는 오류 수정 내용을 develop 브랜치에 병합
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicinePrescriptionListGet.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicinePrescriptionService.java
Labels: bug

#153 회원 프로필 이미지 기능 구현
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/user/UserController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/User.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/familyMember/FamilyMember.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/familyMember/FamilyMemberInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/inquiry/PatientInfoInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/inquiry/PatientInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/inquiry/ProtectorInfoInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/userProfileImage/UserProfileImageDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/userProfileImage/UserProfileImageUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/service/user/UserService.java
Labels: enhancement

#154 whisper api 구현
  build.gradle
  src/main/java/org/mansumugang/mansumugang_service/MansumugangServiceApplication.java
  src/main/java/org/mansumugang/mansumugang_service/model/request/ChatGPTRequest.java
  src/main/java/org/mansumugang/mansumugang_service/model/request/ChatRequest.java
  src/main/java/org/mansumugang/mansumugang_service/model/request/Message.java
  src/main/java/org/mansumugang/mansumugang_service/model/request/TranscriptionRequest.java
  src/main/java/org/mansumugang/mansumugang_service/model/request/WhisperTranscriptionRequest.java
  src/main/java/org/mansumugang/mansumugang_service/model/response/ChatGPTResponse.java
  src/main/java/org/mansumugang/mansumugang_service/model/response/Choice.java
  src/main/java/org/mansumugang/mansumugang_service/model/response/Usage.java
  src/main/java/org/mansumugang/mansumugang_service/model/response/WhisperTranscriptionResponse.java
  src/main/java/org/mansumugang/mansumugang_service/openaiclient/OpenAIClient.java
  src/main/java/org/mansumugang/mansumugang_service/openaiclient/OpenAIClientConfig.java
  src/main/java/org/mansumugang/mansumugang_service/restcontroller/OpenAIClientController.java
  src/main/java/org/mansumugang/mansumugang_service/service/OpenAIClientService.java
Labels: enhancement

#155 구현한 프로필 이미지 기능을 develop 브랜치에 병합 요청
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/user/UserController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/User.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/familyMember/FamilyMember.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/familyMember/FamilyMemberInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/inquiry/PatientInfoInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/inquiry/PatientInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/inquiry/ProtectorInfoInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/userProfileImage/UserProfileImageDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/userProfileImage/UserProfileImageUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/service/user/UserService.java
Labels: enhancement

#156 회원 관련 기능 추가 작업 완료.
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/user/UserController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/user/User.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/comment/CommentInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/reply/ReplyInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/medicine/MedicinePrescriptionListGet.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/familyMember/FamilyMember.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/familyMember/FamilyMemberInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/inquiry/PatientInfoInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/inquiry/PatientInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/inquiry/ProtectorInfoInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/userProfileImage/UserProfileImageDelete.java
  src/main/java/org/mansumugang/mansumugang_service/dto/user/userProfileImage/UserProfileImageUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/CommentService.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/ReplyService.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/post/PostService.java
  src/main/java/org/mansumugang/mansumugang_service/service/medicine/MedicinePrescriptionService.java
  src/main/java/org/mansumugang/mansumugang_service/service/record/RecordService.java
  src/main/java/org/mansumugang/mansumugang_service/service/user/UserService.java
Labels: enhancement

#157 enhance-for-user -> develop 브랜치로 병합 요청
  src/main/java/org/mansumugang/mansumugang_service/dto/community/comment/CommentInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/reply/ReplyInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/CommentService.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/ReplyService.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/post/PostService.java
  src/main/java/org/mansumugang/mansumugang_service/service/record/RecordService.java
Labels: enhancement

#159 음성녹음 저장시 Whisper API를 통한 텍스트 변환 기능 추가 구현.
  src/main/java/org/mansumugang/mansumugang_service/config/OpenAIClient.java
  src/main/java/org/mansumugang/mansumugang_service/config/OpenAIClientConfig.java
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/record/RecordController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/user/OpenAIClientController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Comment.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Post.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Reply.java
  src/main/java/org/mansumugang/mansumugang_service/domain/hospital/Hospital.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/Medicine.java
  src/main/java/org/mansumugang/mansumugang_service/domain/record/Record.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordSave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/Transcription.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/WhisperTranscription.java
  src/main/java/org/mansumugang/mansumugang_service/openaiclient/OpenAIClient.java
  src/main/java/org/mansumugang/mansumugang_service/repository/RecordRepository.java
  src/main/java/org/mansumugang/mansumugang_service/restcontroller/OpenAIClientController.java
  src/main/java/org/mansumugang/mansumugang_service/service/record/OpenAIClientService.java
  src/main/java/org/mansumugang/mansumugang_service/service/record/RecordService.java
Labels: enhancement

#161 음성녹음 저장시 Whisper API를 통한 텍스트 변환 기능 추가 구현.
  build.gradle
  src/main/java/org/mansumugang/mansumugang_service/MansumugangServiceApplication.java
  src/main/java/org/mansumugang/mansumugang_service/config/OpenAIClient.java
  src/main/java/org/mansumugang/mansumugang_service/config/OpenAIClientConfig.java
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/record/RecordController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/user/OpenAIClientController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Comment.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Post.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Reply.java
  src/main/java/org/mansumugang/mansumugang_service/domain/hospital/Hospital.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/Medicine.java
  src/main/java/org/mansumugang/mansumugang_service/domain/record/Record.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordSave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/Transcription.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/WhisperTranscription.java
  src/main/java/org/mansumugang/mansumugang_service/repository/RecordRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/record/OpenAIClientService.java
  src/main/java/org/mansumugang/mansumugang_service/service/record/RecordService.java
Labels: enhancement

#162 Feature/whisper -> develop 브랜치 병합 요청
  build.gradle
  src/main/java/org/mansumugang/mansumugang_service/MansumugangServiceApplication.java
  src/main/java/org/mansumugang/mansumugang_service/config/OpenAIClient.java
  src/main/java/org/mansumugang/mansumugang_service/config/OpenAIClientConfig.java
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/record/RecordController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/user/OpenAIClientController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Comment.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Post.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Reply.java
  src/main/java/org/mansumugang/mansumugang_service/domain/hospital/Hospital.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/Medicine.java
  src/main/java/org/mansumugang/mansumugang_service/domain/record/Record.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordSave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/Transcription.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/WhisperTranscription.java
  src/main/java/org/mansumugang/mansumugang_service/repository/RecordRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/record/OpenAIClientService.java
  src/main/java/org/mansumugang/mansumugang_service/service/record/RecordService.java
Labels: enhancement

#165 163-request-from-frontend -> develop 브랜치 병합요청
  src/main/java/org/mansumugang/mansumugang_service/controller/community/PostController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/record/RecordController.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordSaveLimit.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/post/PostService.java
  src/main/java/org/mansumugang/mansumugang_service/service/record/RecordService.java
Labels: enhancement

#166 현재까지 구현된 기능을 main 브랜치에 병합
  build.gradle
  src/main/java/org/mansumugang/mansumugang_service/MansumugangServiceApplication.java
  src/main/java/org/mansumugang/mansumugang_service/config/OpenAIClient.java
  src/main/java/org/mansumugang/mansumugang_service/config/OpenAIClientConfig.java
  src/main/java/org/mansumugang/mansumugang_service/constant/ErrorType.java
  src/main/java/org/mansumugang/mansumugang_service/controller/community/PostController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/record/RecordController.java
  src/main/java/org/mansumugang/mansumugang_service/controller/user/OpenAIClientController.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Comment.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Post.java
  src/main/java/org/mansumugang/mansumugang_service/domain/community/Reply.java
  src/main/java/org/mansumugang/mansumugang_service/domain/hospital/Hospital.java
  src/main/java/org/mansumugang/mansumugang_service/domain/medicine/Medicine.java
  src/main/java/org/mansumugang/mansumugang_service/domain/record/Record.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/post/PostUpdate.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordSave.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordSaveLimit.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/Transcription.java
  src/main/java/org/mansumugang/mansumugang_service/dto/record/WhisperTranscription.java
  src/main/java/org/mansumugang/mansumugang_service/repository/RecordRepository.java
  src/main/java/org/mansumugang/mansumugang_service/service/community/post/PostService.java
  src/main/java/org/mansumugang/mansumugang_service/service/record/OpenAIClientService.java
  src/main/java/org/mansumugang/mansumugang_service/service/record/RecordService.java
Labels: enhancement

#168 fix:댓글, 대댓글 삭제 후 조회할 경우 오류에 대한 코드 수정
  src/main/java/org/mansumugang/mansumugang_service/dto/community/comment/CommentInquiry.java
  src/main/java/org/mansumugang/mansumugang_service/dto/community/reply/ReplyInquiry.java
Labels: bug
